#!/usr/bin/env node
/**
 * Generate the player-facing docs from the pack itself.
 *
 *   node tools/gen-docs.js
 *
 * Everything here is DERIVED. Nothing in docs/usage/ is written by hand, because
 * a hand-maintained mod list or quest list is wrong the moment a mod is added:
 * the old root MODS.md still advertised Dramatic Doors and had never heard of
 * Squat Grow. The sources of authority are:
 *
 *   tools/mods.json                     what the pack declares, and why things left
 *   packs/<name>-<version>.mrpack       what actually shipped, with exact versions
 *   overrides/config/boundless/...      the quest book, verbatim
 *   overrides/config/defaultoptions/    the keybinds players actually get
 *
 * Re-run it after any change to those. CI does this on every push, so a stale
 * doc shows up as a dirty tree rather than silently misleading someone.
 */
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const DOCS = path.join(ROOT, 'docs', 'usage');
const data = JSON.parse(fs.readFileSync(path.join(ROOT, 'tools', 'mods.json'), 'utf8'));
const VERSION = data.pack.version;

const write = (rel, body) => {
  const p = path.join(DOCS, rel);
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, body.replace(/\n{3,}/g, '\n\n').trimEnd() + '\n');
  console.log(`  wrote docs/usage/${rel}`);
};

const STAMP = (extra) =>
  `<!-- GENERATED by tools/gen-docs.js from ${extra}. Do not edit by hand. -->\n\n`;

// ---------------------------------------------------------------- mod list ---
function modList(jarCount) {
  const mrpack = path.join(ROOT, 'packs', `tinker-and-create-${VERSION}.mrpack`);
  let files = [];
  if (fs.existsSync(mrpack)) {
    const idx = JSON.parse(execSync(`unzip -p ${JSON.stringify(mrpack)} modrinth.index.json`).toString());
    files = idx.files || [];
  }

  // Exact shipped jars, keyed by filename, so versions come from the artifact
  // rather than from anyone's memory of what was current.
  const jars = files
    .filter((f) => f.path.endsWith('.jar'))
    .map((f) => ({
      file: path.basename(f.path),
      client: (f.env && f.env.client) || 'required',
      server: (f.env && f.env.server) || 'required',
    }))
    .sort((a, b) => a.file.localeCompare(b.file));

  const byCat = {};
  for (const m of data.mods || []) (byCat[m.category] = byCat[m.category] || []).push(m);
  const cats = Object.keys(byCat).sort();

  let s = STAMP('tools/mods.json and the built .mrpack');
  s += `# Mod list\n\n`;
  s += `**Tinker & Create ${VERSION}** — Minecraft ${data.pack.minecraft}, ${data.pack.loader} ${data.pack.loaderVersion}.\n\n`;
  // Read the count back from the committed jar list rather than from this
  // build. Otherwise the sentence says 339 on a machine that has built the pack
  // and 0 on a clean checkout, and the docs check fails on the difference.
  s += `${jarCount} jars ship in the pack: ${data.mods.length} are declared in \`tools/mods.json\`, `;
  s += `the rest are dependencies the build resolves automatically. Mod menus report a higher number `;
  s += `still — Create alone bundles Flywheel, Ponder and Registrate inside its own jar, and those `;
  s += `nested libraries count as mods once loaded.\n\n`;

  s += `## By category\n\n`;
  for (const c of cats) {
    s += `### ${c}\n\n`;
    for (const m of byCat[c].sort((a, b) => a.name.localeCompare(b.name))) {
      s += `- [${m.name}](https://modrinth.com/mod/${m.slug})\n`;
    }
    s += `\n`;
  }

  s += `The exact jar versions that shipped are in [shipped-jars.md](shipped-jars.md).\n\n`;

  const removed = data.removed || [];
  if (removed.length) {
    s += `## Removed, and why\n\n`;
    s += `Kept as a record so the same mod is not re-proposed without the reason it left.\n\n`;
    for (const r of removed) s += `- **${r.name}** (\`${r.slug}\`) — ${r.reason}\n`;
    s += `\n`;
  }

  const groups = data.exclusiveGroups || [];
  if (groups.length) {
    s += `## Mutually exclusive choices\n\n`;
    for (const g of groups) {
      s += `- **${g.label}** — keeps \`${g.keep}\` over ${g.members.filter((m) => m !== g.keep).map((m) => `\`${m}\``).join(', ')}. ${g.reason}\n`;
    }
    s += `\n`;
  }
  return { body: s, jars };
}

/**
 * The exact jar list is kept in its own file, and is NOT part of the
 * "docs are current" equality check.
 *
 * It cannot be: it records the versions the resolver picked at build time, and
 * the resolver picks the newest compatible build. An upstream release between
 * one build and the next changes this file with nothing in the repository
 * having changed -- CI caught exactly that, supplementaries 3.8.8 locally
 * against 3.8.9 on the runner, and failed a run that was not wrong. Checking it
 * for equality would mean a red build every time any of ~340 mods updates.
 *
 * So: regenerate it whenever a built pack is present (locally, and on publish),
 * and when there is no pack, keep whatever was committed. That also makes the
 * mod-count badge deterministic, since the count is read back from here.
 */
function shippedJars(jars) {
  let s = STAMP('the built .mrpack');
  s += `# Shipped jars\n\n`;
  s += `Every jar in **${VERSION}**, with the version each was resolved to at build time.\n\n`;
  s += `This file is refreshed when the pack is built, so it tracks releases upstream. `;
  s += `It is deliberately excluded from the docs-are-current check — the resolver takes `;
  s += `the newest compatible build of each mod, so this changes on its own whenever any `;
  s += `of them publishes, with nothing here having changed.\n\n`;
  s += `| Jar | Client | Server |\n|---|---|---|\n`;
  for (const j of jars) s += `| \`${j.file}\` | ${j.client} | ${j.server} |\n`;
  return s;
}

/** Count rows in the committed shipped-jars.md, so the badge works without a build. */
function committedJarCount() {
  const p = path.join(DOCS, 'shipped-jars.md');
  if (!fs.existsSync(p)) return 0;
  return (fs.readFileSync(p, 'utf8').match(/^\| `[^`]+\.jar` \|/gm) || []).length;
}

// -------------------------------------------------------------- quest book ---
function questBook() {
  const base = path.join(ROOT, 'overrides/config/boundless/questpacks/tinker_and_create/data/tinkercreate/quests');
  const readJson = (p) => JSON.parse(fs.readFileSync(p, 'utf8'));

  const catDir = path.join(base, 'categories');
  const cats = fs.existsSync(catDir)
    ? fs.readdirSync(catDir).filter((f) => f.endsWith('.json')).map((f) => readJson(path.join(catDir, f)))
    : [];
  cats.sort((a, b) => (a.order || 0) - (b.order || 0));

  const quests = fs.readdirSync(base).filter((f) => f.endsWith('.json')).map((f) => readJson(path.join(base, f)));
  const nameById = Object.fromEntries(quests.map((q) => [q.id, q.name]));

  // Boundless keys targets by verb, so read the verb rather than a kind field.
  const objective = (t) => {
    const n = t.count && t.count > 1 ? ` ×${t.count}` : '';
    if (t.collect) return `Have \`${t.collect}\`${n}`;
    if (t.submit) return `Hand in \`${t.submit}\`${n}`;
    if (t.kill) return `Kill \`${t.kill}\`${n}`;
    if (t.achieve) return `Earn advancement \`${t.achieve}\``;
    if (t.effect) return `Gain effect \`${t.effect}\``;
    if (t.stat) return `Reach stat \`${t.stat}\`${n}`;
    if (t.xp) return `Reach ${t.count} ${t.xp}`;
    return '`' + JSON.stringify(t) + '`';
  };

  const rewards = (r) => {
    if (!r) return [];
    const out = [];
    for (const i of r.items || []) out.push(`\`${i.item}\`${i.count > 1 ? ` ×${i.count}` : ''}`);
    if (r.count) out.push(`${r.count} ${r.exp || 'points'} XP`);
    for (const c of r.commands || []) {
      // Prefer the reward's own title -- it is what the button says in game.
      // Dumping the raw command is both ugly and misleading: the welcome quest's
      // is a 900-character /give with an embedded written_book NBT payload.
      const m = /^\/ponder\s+(\S+)/.exec(c.command || '');
      if (m) out.push(`Ponder scene \`${m[1]}\``);
      else if (c.title) out.push(c.title);
      else out.push(`\`${(c.command || '').slice(0, 48)}…\``);
    }
    for (const f of r.functions || []) out.push(`function \`${f.function}\``);
    return out;
  };

  let s = STAMP('the Boundless questpack in overrides/config/boundless');
  s += `# Quest book\n\n`;
  s += `${quests.length} quests across ${cats.length} categories, as they appear in game. `;
  s += `Open it from the button in your inventory, above the offhand slot, or press \`]\`.\n\n`;
  s += `Rewards are **not** claimed automatically — a quest completes, then you claim it. `;
  s += `Nothing here is a spoiler you could not read in the book itself.\n\n`;

  for (const c of cats) {
    const mine = quests.filter((q) => q.category === c.id);
    if (!mine.length) continue;
    s += `## ${c.name}\n\n`;
    for (const q of mine.sort((a, b) => (a.dependencies || []).length - (b.dependencies || []).length)) {
      const flags = [];
      if (q.optional) flags.push('optional');
      if (q.repeatable) flags.push('repeatable');
      s += `### ${q.name}${flags.length ? ` _(${flags.join(', ')})_` : ''}\n\n`;
      if (q.description) s += `${String(q.description).replace(/\n+/g, ' ').trim()}\n\n`;
      const deps = (q.dependencies || []).map((d) => nameById[d] || d);
      if (deps.length) s += `- **Requires:** ${deps.join(', ')}\n`;
      const tg = (q.completion && q.completion.complete) || [];
      if (tg.length) s += `- **Objective:** ${tg.map(objective).join('; ')}\n`;
      const rw = rewards(q.reward);
      if (rw.length) s += `- **Reward:** ${rw.join(', ')}\n`;
      s += `\n`;
    }
  }
  return { body: s, questCount: quests.length };
}

// ---------------------------------------------------------------- keybinds ---
function keybinds() {
  const p = path.join(ROOT, 'overrides/config/defaultoptions/keybindings.txt');
  if (!fs.existsSync(p)) return null;
  const rows = [];
  for (const line of fs.readFileSync(p, 'utf8').split('\n')) {
    if (!line.startsWith('key_')) continue;
    const i = line.indexOf(':');
    const name = line.slice(0, i).replace(/^key_/, '');
    const value = line.slice(i + 1).trim();
    if (value.startsWith('key.keyboard.unknown')) continue;
    const key = value.replace(/^key\.keyboard\./, '').replace(/^key\.mouse\./, 'mouse ').replace(/\./g, ' ');
    rows.push({ name, key });
  }
  rows.sort((a, b) => a.key.localeCompare(b.key) || a.name.localeCompare(b.name));

  let s = STAMP('overrides/config/defaultoptions/keybindings.txt');
  s += `# Keybinds\n\n`;
  s += `These are the defaults the pack ships. Default Options applies them on **first launch only**, `;
  s += `so if you have played before, your own \`options.txt\` wins and these are just a reference.\n\n`;
  s += `${rows.length} bound actions. Anything not listed is deliberately unbound to stop two mods `;
  s += `fighting over one key — rebind them yourself in Options → Controls.\n\n`;
  s += `| Key | Action |\n|---|---|\n`;
  for (const r of rows) s += `| \`${r.key}\` | ${r.name} |\n`;
  return s;
}

// ------------------------------------------------------------- badge sync ---
/**
 * The mod-count badge is a number embedded in prose, which is the most
 * reliable way to end up lying: README advertised 333 while the pack shipped
 * 339. Rewrite it from the artifact instead, in both places it appears, and
 * repoint the old root MODS.md links at the generated doc.
 */
function syncBadges(jarCount, questCount) {
  const GH = 'https://github.com/ryancircelli/tinker-and-create-mods/blob/master';
  const targets = [
    { file: path.join(ROOT, 'README.md'), mods: 'docs/usage/mods.md', quests: 'docs/usage/quest-book.md' },
    {
      file: path.join(ROOT, 'modrinth-description.md'),
      mods: `${GH}/docs/usage/mods.md`,
      quests: `${GH}/docs/usage/quest-book.md`,
    },
  ];
  for (const t of targets) {
    if (!fs.existsSync(t.file)) continue;
    const before = fs.readFileSync(t.file, 'utf8');
    const after = before
      .replace(/badge\/mods-\d+-blue/g, `badge/mods-${jarCount}-blue`)
      .replace(/badge\/quests-\d+-purple/g, `badge/quests-${questCount}-purple`)
      // Retarget the old root MODS.md links at the generated doc.
      .replace(/\]\((?:\.\/)?MODS\.md\)/g, `](${t.mods})`)
      .replace(/\]\(https:\/\/github\.com\/[^)]*\/blob\/master\/MODS\.md\)/g, `](${t.mods})`)
      // The quests badge pointed at Questlog, which is no longer in the pack.
      // Point it at the generated quest book instead of another mod page, so it
      // cannot go stale again when the quest mod changes.
      .replace(/\]\(https:\/\/modrinth\.com\/mod\/questlog\)/g, `](${t.quests})`);
    if (after !== before) {
      fs.writeFileSync(t.file, after);
      console.log(`  synced ${path.relative(ROOT, t.file)} (mods-${jarCount}, quests-${questCount})`);
    }
  }
}

fs.mkdirSync(DOCS, { recursive: true });
const mods = modList(committedJarCount());
write('mods.md', mods.body);
const qb = questBook();
write('quest-book.md', qb.body);
const kb = keybinds();
if (kb) write('keybinds.md', kb);

// Only rewrite the jar list when a built pack is actually present. Without this
// guard a docs run on a clean checkout would blank the committed file.
if (mods.jars.length) write('shipped-jars.md', shippedJars(mods.jars));
syncBadges(committedJarCount(), qb.questCount);
